FROM jfloff/alpine-python

COPY ./requirements.txt /app/requirements.txt

COPY ./app.py /app/app.py

COPY ./test.py /app/test.py

RUN pip install -r /app/requirements.txt

WORKDIR /app/

CMD python -m tornado.testing test
